services:
  ws:
    build: .
    ports:
      - "8080:80"
    volumes:
      - "./public:/var/www/html"
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: Passw0rd
      MARIADB_DATABASE: autorent
    volumes:
      - "./db_data:/var/lib/mysql"

  dbm:
    image: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"